### ISSUE TITLE
Can't compile with Clang 12.0.1 and -std=c++20

### ISSUE THREAD

**Issue by eklitzke** [jinja2cpp/Jinja2Cpp#213]
When I try to build the latest commit 171b5bd970579bb387ad49703fad0313eaf0e1f3 using clang 12.0.1 with c++20 I get a lot of build errors like:
```
external/jinja2cpp/src/error_info.cpp:119:45: error: call to consteval function 'fmt::basic_format_string<char, std::string, const unsigned int &, const unsigned int &>::basic_format_string<std::string, 0>' is not a constant expression
    fmt::format_to(std::back_inserter(out), UNIVERSAL_STR("{}:{}:{}: error: ").GetValue<CharT>(), ConvertString<string_t>(loc.fileName), loc.line, loc.col);
                                            ^
external/jinja2cpp/src/helpers.h:49:5: note: expanded from macro 'UNIVERSAL_STR'
    ::jinja2::MultiStringLiteral { Str, L##Str }
    ^
external/jinja2cpp/src/error_info.cpp:262:5: note: in instantiation of function template specialization 'jinja2::RenderErrorInfo<char>' requested here
    RenderErrorInfo(result, *this);
    ^
external/jinja2cpp/src/error_info.cpp:119:45: note: non-literal type 'std::string' cannot be used in a constant expression
    fmt::format_to(std::back_inserter(out), UNIVERSAL_STR("{}:{}:{}: error: ").GetValue<CharT>(), ConvertString<string_t>(loc.fileName), loc.line, loc.col);
                                            ^
external/jinja2cpp/src/helpers.h:49:5: note: expanded from macro 'UNIVERSAL_STR'
    ::jinja2::MultiStringLiteral { Str, L##Str }
    ^
external/jinja2cpp/src/error_info.cpp:124:48: error: call to consteval function 'fmt::basic_format_string<char>::basic_format_string<std::string, 0>' is not a constant expression
            format_to(std::back_inserter(out), UNIVERSAL_STR("Parse error").GetValue<CharT>());
                                               ^
external/jinja2cpp/src/helpers.h:49:5: note: expanded from macro 'UNIVERSAL_STR'
    ::jinja2::MultiStringLiteral { Str, L##Str }
    ^
external/jinja2cpp/src/error_info.cpp:124:48: note: non-literal type 'std::string' cannot be used in a constant expression
external/jinja2cpp/src/helpers.h:49:5: note: expanded from macro 'UNIVERSAL_STR'
    ::jinja2::MultiStringLiteral { Str, L##Str }
    ^
external/jinja2cpp/src/error_info.cpp:129:44: error: call to consteval function 'fmt::basic_format_string<char, const jinja2::Value &>::basic_format_string<std::string, 0>' is not a constant expression
        format_to(std::back_inserter(out), UNIVERSAL_STR("Unexpected exception occurred during template processing. Exception: {}").GetValue<CharT>(), extraParams[0]);
                                           ^
external/jinja2cpp/src/helpers.h:49:5: note: expanded from macro 'UNIVERSAL_STR'
    ::jinja2::MultiStringLiteral { Str, L##Str }
    ^
external/jinja2cpp/src/error_info.cpp:129:44: note: non-literal type 'std::string' cannot be used in a constant expression
external/jinja2cpp/src/helpers.h:49:5: note: expanded from macro 'UNIVERSAL_STR'
    ::jinja2::MultiStringLiteral { Str, L##Str }
    ^
```

**Comment by luismartingil** [comment]
@eklitzke Looks like clang-12 is not officially supported in this library (see [docs here](https://github.com/jinja2cpp/Jinja2Cpp#supported-compilers))?

**Comment by eklitzke** [comment]
Just to be clear, the code does compile with clang 12 using `-std=c++17`, this is specifically an issue with the combination of clang 12 and `-std=c++20` (note, I haven't tried clang 13 yet). For now I am just using the older version of jinja2cpp which does compile with `-std=c++20`.

**Comment by luismartingil** [comment]
@eklitzke Are you planning on a PR to fix this issue?

**Comment by rmorozov** [comment]
@luismartingil, @eklitzke , I've made an attempt to fix it in https://github.com/jinja2cpp/Jinja2Cpp/pull/216.
You are welcome for review, locally it builds successfully with clang 12.0.1 -std=c++20.

I've added CI build with clang-12, think it would handy to have build support with modern c++ standard
